name: Cypress Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Verify Cypress installation
        run: npx cypress verify
        
      - name: Run tests
        run: npx cypress run --browser chrome --config-file config/cypress.config.ts
        run: npx cypress run --browser edge --config-file config/cypress.config.edge.ts
